# Generated by Django 3.2.19 on 2023-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('semester', models.CharField(default='', max_length=50)),
                ('section', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('regulation', models.CharField(default='', max_length=50)),
                ('isattended', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('regulation', models.CharField(max_length=50)),
            ],
        ),
    ]
