# Generated by Django 3.2.19 on 2023-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halticket_number', models.CharField(default='', max_length=50)),
                ('Subject_Code', models.CharField(default='', max_length=50)),
                ('Subject_Name', models.CharField(default='', max_length=50)),
                ('Internal_Marks', models.CharField(default='', max_length=50)),
                ('ExterNal_Marks', models.CharField(default='', max_length=50)),
                ('Total', models.CharField(default='', max_length=50)),
                ('Credits', models.CharField(default='', max_length=50)),
                ('year_sem', models.CharField(default='', max_length=50)),
                ('actualmarks', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
