# Generated by Django 3.2.19 on 2023-07-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_marksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='regulation',
        ),
    ]
