# Generated by Django 3.2.19 on 2023-07-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_attendancemodel_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halticket_number', models.CharField(default='', max_length=50)),
                ('Company_Name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
